<a href="https://colab.research.google.com/github/prasannakumar08/Prasannakumar_INFO5731_Spring2021/blob/main/Universities_Crawl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##Question 2 (12 points): Write python code to collect 500 items of the data you plan to collect above.

import time
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
path = '/home/prasanna/crawl'
number = (list(range(0, 522, 18)))
a = []
b = []


for i in number:
    url = 'https://www.collegesimply.com/colleges/search?sort=&place=&gpa=&sat=&act=&field=computer-and-information-sciences-and-support-services&major=&radius=300&zip=&state=&size=&tuition-fees=&net-price=&start='+str(i)
    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser")
    
    for hit in soup.findAll("a", itemprop="url"):
        name_dict = hit.attrs
        onclick_str = name_dict['onclick']
        splt_name = onclick_str.split("'")
        name = splt_name[7]
        a.append(name)
        
    for ultag in soup.find_all('ul', {'class': 'list-inline text-sm mb-3 text-muted'}):
        for litag in ultag.find_all('li', {'class': 'list-inline-item mr-3'}):
            for data in litag.find_all('span', {'class': 'mr-1 h6 text-dark'}):
                score = (data.text)
                b.append(score)

univ_name = pd.DataFrame(a)
score = pd.DataFrame(np.array(b).reshape(-1,6),columns=['Enrollment','Net Range','Acceptance Rate','SAT Range','ACT Range','AVG GPA'])

univ = pd.concat([univ_name, score.reindex(univ_name.index)], axis=1)
univ= univ.rename(columns = {0:'University'})

In [ ]:
univ

,University,Enrollment,Acceptance Rate,SAT Range,ACT Range,AVG GPA,Net Range
0,Harvard University,"31,566",5%,1460-1570,33-35,4.04,"18,030 dollars"
1,Stanford University,"17,381",4%,1440-1570,32-35,4.18,"16,779 dollars"
2,University of Florida,"52,218",37%,1310-1470,28-33,4.1,"10,457 dollars"
3,The University of Texas at Austin,"51,832",32%,1230-1480,27-33,3.8*,"15,502 dollars"
4,University of Michigan,"46,716",23%,1340-1530,31-34,3.82,"17,357 dollars"
5,University of California Los Angeles,"44,537",12%,1300-1530,29-35,4.29,"15,718 dollars"
6,Florida State University,"41,005",36%,1200-1340,26-30,3.88,"12,568 dollars"
7,Clemson University,"24,951",51%,1230-1400,27-32,4.18,"21,482 dollars"
8,University of Southern California,"47,310",11%,1360-1530,31-34,3.73,"37,521 dollars"
9,University of Miami,"17,331",27%,1270-1440,29-32,4.2,"33,102 dollars"
10,Arizona State University,"51,585",86%,1120-1360,22-28,3.42,"14,081 dollars"
11,University of Georgia,"38,652",45%,1240-1420,27-32,3.86,"15,961 dollars"
12,Penn State Main Campus,"46,810",76%,1070-1310,23-30,3.59,"24,724 dollars"
13,University of North Carolina at Chapel Hill,"30,011",23%,1310-1500,28-33,4.6,"10,085 dollars"
14,Virginia Tech,"34,683",70%,1180-1390,25-31,3.95,"18,449 dollars"
15,New York University,"51,847",16%,1350-1530,30-34,3.6,"37,739 dollars"
16,Duke University,"16,606",8%,1480-1570,33-35,3.94*,"24,386 dollars"
17,Vanderbilt University,"12,824",9%,1460-1560,33-35,3.76,"25,855 dollars"
18,Michigan State University,"50,351",71%,1100-1320,23-29,3.62,"16,579 dollars"
19,Johns Hopkins University,"26,152",11%,1460-1560,33-35,3.74,"28,999 dollars"
20,The University of Alabama,"38,390",83%,1080-1340,23-31,3.6,"20,623 dollars"
21,University of Central Florida,"68,475",44%,1170-1340,25-30,3.81,"11,617 dollars"
22,San Diego State University,"35,303",34%,1110-1320,22-29,3.6,"14,499 dollars"
23,Boston University,"34,657",19%,1340-1510,30-34,3.59,"29,479 dollars"
24,Auburn University,"30,440",81%,1150-1320,25-31,3.74,"23,562 dollars"
25,Ohio State University,"61,170",54%,1250-1460,28-32,3.76*,"18,706 dollars"
26,University of California Irvine,"36,032",27%,1170-1420,24-33,3.92,"15,268 dollars"
27,University of Pennsylvania,"25,860",8%,1450-1560,33-35,3.9,"24,771 dollars"
28,Yale University,"13,433",6%,1460-1570,33-35,3.95*,"18,073 dollars"
29,University of Chicago,"17,002",6%,1500-1570,33-35,4.0,"34,719 dollars"
30,Baylor University,"17,217",45%,1200-1380,26-32,3.74*,"38,372 dollars"
31,University of Maryland College Park,"41,200",44%,1280-1470,29-34,4.11,"17,723 dollars"
32,University of Wisconsin Madison,"43,463",54%,1300-1480,27-32,3.84,"16,103 dollars"
33,University of Washington Seattle Campus,"47,400",52%,1220-1470,27-33,3.75,"10,692 dollars"
34,The University of Tennessee,"28,894",79%,1150-1330,24-30,3.85,"21,024 dollars"
35,North Carolina State University at Raleigh,"35,479",45%,1250-1420,27-32,4.37,"14,958 dollars"
36,University of Kentucky,"29,182",96%,1070-1320,22-29,3.46,"18,958 dollars"
37,Villanova University,"11,030",28%,1320-1470,31-34,3.86,"36,840 dollars"
38,University of California Berkeley,"42,501",16%,1330-1530,31-35,3.86,"18,522 dollars"
39,Purdue University Main Campus,"44,474",60%,1190-1440,25-32,3.7,"12,684 dollars"
40,University of California Santa Barbara,"25,976",30%,1230-1480,27-34,3.96,"16,767 dollars"
41,Cornell University,"23,600",11%,1400-1560,32-35,3.9*,"28,921 dollars"
42,University of Virginia Main Campus,"24,639",24%,1340-1520,30-34,4.22,"17,579 dollars"
43,Texas A & M University College Station,"68,679",58%,1160-1390,26-31,3.68*,"19,237 dollars"
44,East Carolina University,"28,718",79%,1040-1190,20-24,3.59,"13,635 dollars"
45,University of Hawaii at Manoa,"17,710",58%,1070-1270,21-26,3.46,"15,441 dollars"
46,University of Arizona,"44,097",85%,1110-1360,21-29,3.42,"16,580 dollars"
47,Kennesaw State University,"24,176",62%,1070-1250,21-24,3.22,"15,451 dollars"
48,University of Colorado Boulder,"36,681",78%,1140-1360,25-31,3.56,"22,077 dollars"
49,Texas State University,"38,644",81%,1010-1180,19-25,3.38*,"13,178 dollars"
50,Texas Tech University,"38,209",69%,1070-1260,22-27,3.49*,"16,463 dollars"
51,University of Houston,"46,324",65%,1140-1310,22-27,3.54*,"13,212 dollars"
52,Georgia State University,"34,316",76%,1060-1250,20-26,3.34,"14,136 dollars"
53,University of California Davis,"38,167",39%,1170-1410,24-32,3.99,"15,886 dollars"
54,Georgetown University,"19,204",14%,1380-1550,31-35,3.89*,"28,442 dollars"
55,Northwestern University,"22,127",9%,1440-1550,33-35,3.92*,"26,196 dollars"
56,University of South Carolina Columbia,"34,795",69%,1180-1370,25-31,4.15,"21,787 dollars"
57,San Jose State University,"35,400",64%,1020-1260,18-27,3.31,"14,471 dollars"
58,Georgia Institute of Technology Main Campus,"32,723",21%,1300-1510,29-34,3.95,"16,883 dollars"
59,University of Notre Dame,"12,607",16%,1400-1550,32-35,3.91*,"30,536 dollars"
60,California State University Long Beach,"37,466",39%,1040-1250,20-26,3.5,"9,903 dollars"
61,The University of Tampa,"9,333",45%,1100-1250,23-28,3.3,"31,278 dollars"
62,Appalachian State University,"19,108",77%,1100-1270,22-28,4.05,"10,525 dollars"
63,Emory University,"14,458",16%,1360-1530,31-34,3.8,"25,942 dollars"
64,Colorado State University Fort Collins,"33,478",81%,1070-1290,23-29,3.61,"16,793 dollars"
65,Howard University,"9,139",36%,1130-1280,22-27,3.54*,"21,428 dollars"
66,University of California San Diego,"37,887",31%,1250-1490,26-34,3.82*,"14,864 dollars"
67,Carnegie Mellon University,"14,029",15%,1460-1560,33-35,3.69,"30,618 dollars"
68,Temple University,"39,740",60%,-,-,3.41,"23,032 dollars"
69,University of Delaware,"24,120",71%,1160-1350,24-30,3.5,"17,539 dollars"
70,Syracuse University,"22,803",44%,1180-1380,26-30,3.6,"43,111 dollars"
71,Florida Atlantic University,"29,772",63%,1080-1240,22-26,3.46,"9,861 dollars"
72,George Mason University,"37,316",87%,1110-1320,24-30,3.66,"20,157 dollars"
73,San Francisco State University,"29,778",67%,940-1150,17-23,3.2,"15,166 dollars"
74,Washington State University,"31,478",76%,1020-1230,20-26,3.3,"18,002 dollars"
75,Miami University,"19,934",80%,1190-1390,25-30,3.63,"22,989 dollars"
76,Rice University,"7,124",9%,1470-1570,33-35,3.96*,"20,335 dollars"
77,Boston College,"14,720",27%,1340-1500,31-34,3.86*,"28,354 dollars"
78,Brown University,"10,257",7%,1440-1570,33-35,3.94*,"27,218 dollars"
79,University of Oregon,"22,644",82%,1100-1310,22-28,3.6,"16,080 dollars"
80,Indiana University Bloomington,"43,503",78%,1150-1360,24-31,3.62,"13,036 dollars"
81,Oregon State University,"30,986",82%,1080-1320,21-28,3.56,"19,273 dollars"
82,Stony Brook University,"26,256",44%,1230-1440,26-32,3.8,"15,605 dollars"
83,Iowa State University,"34,992",92%,1100-1340,22-28,3.6,"15,195 dollars"
84,SUNY at Binghamton,"17,768",41%,1280-1440,29-32,3.6,"17,424 dollars"
85,University of Massachusetts Amherst,"30,593",64%,1190-1390,26-32,3.73,"22,927 dollars"
86,Massachusetts Institute of Technology,"11,574",7%,1510-1570,34-36,3.96*,"20,465 dollars"
87,University of San Francisco,"10,713",64%,1130-1330,23-29,3.61,"38,422 dollars"
88,Northeastern University,"21,627",18%,1390-1540,32-35,3.91*,"36,479 dollars"
89,Columbia University in the City of New York,"31,077",5%,1440-1570,33-35,3.91*,"21,828 dollars"
90,United States Air Force Academy,"4,336",11%,1230-1440,28-33,3.88,- dollars
91,Florida Gulf Coast University,"15,031",67%,1060-1210,21-25,3.37,"11,621 dollars"
92,University of Illinois at Urbana Champaign,"49,702",59%,1210-1470,26-32,3.79*,"14,660 dollars"
93,University of Pittsburgh Pittsburgh Campus,"28,673",57%,1260-1440,28-33,3.97,"22,600 dollars"
94,James Madison University,"21,751",77%,1120-1290,23-28,3.57*,"18,708 dollars"
95,University of Illinois at Chicago,"31,683",73%,1030-1260,21-28,3.29,"12,322 dollars"
96,SUNY at Albany,"17,944",54%,1090-1250,22-28,3.5,"16,769 dollars"
97,University of North Texas,"38,241",74%,1060-1250,21-27,3.46*,"14,020 dollars"
98,College of William and Mary,"8,817",38%,1320-1510,30-34,4.12,"18,551 dollars"
99,Loyola Marymount University,"9,838",44%,1230-1410,27-31,3.72,"47,292 dollars"
100,Grand Valley State University,"24,677",83%,1050-1250,21-27,3.52,"16,860 dollars"
101,University of San Diego,"9,073",49%,1190-1370,26-31,3.88,"35,936 dollars"
102,University of South Florida Main Campus,"43,846",48%,1170-1330,25-30,3.86,"9,787 dollars"
103,West Virginia University,"26,864",84%,1030-1230,21-27,3.36,"12,743 dollars"
104,Fordham University,"16,515",46%,1240-1450,28-32,3.59,"39,558 dollars"
105,California State University Los Angeles,"28,036",48%,890-1080,15-20,3.18,"3,255 dollars"
106,George Washington University,"28,172",41%,1280-1470,30-33,3.81*,"38,829 dollars"
107,Santa Clara University,"8,642",49%,1280-1440,28-32,3.66,"42,114 dollars"
108,Elon University,"6,991",78%,1160-1320,25-30,3.99,"36,564 dollars"
109,Boise State University,"25,504",77%,1030-1230,20-26,3.4,"13,237 dollars"
110,California Polytechnic State University San Lu...,"22,013",28%,1240-1440,26-32,3.87,"21,232 dollars"
111,Ball State University,"21,884",77%,-,-,3.42,"13,533 dollars"
112,University of North Carolina at Charlotte,"29,710",65%,1120-1290,22-26,3.82,"15,200 dollars"
113,California State University Fullerton,"40,280",53%,1030-1200,19-24,3.48,"8,294 dollars"
114,The University of Texas at Dallas,"28,755",79%,1240-1460,26-33,3.9,"10,455 dollars"
115,Rutgers University New Brunswick,"50,254",61%,1210-1430,25-32,3.3*,"16,873 dollars"
116,Rutgers University New Brunswick,"50,254",61%,1210-1430,25-32,3.3*,"16,873 dollars"
117,Drexel University,"24,634",75%,1190-1390,25-31,3.6,"38,025 dollars"
118,Spelman College,"2,171",43%,1080-1230,22-26,3.55,"43,042 dollars"
119,California State University Sacramento,"31,902",82%,940-1140,16-22,3.25,"10,271 dollars"
120,Brigham Young University Provo,"34,499",67%,1210-1420,26-31,3.8,"13,340 dollars"
121,Coastal Carolina University,"10,641",69%,1010-1170,19-24,3.4,"15,111 dollars"
122,University of Iowa,"31,656",83%,1130-1340,22-29,3.61,"17,008 dollars"
123,Towson University,"22,923",76%,1060-1220,20-25,3.61,"16,161 dollars"
124,Old Dominion University,"24,176",89%,980-1180,18-24,3.26,"16,681 dollars"
125,University of California Riverside,"23,922",57%,1130-1330,23-30,3.6,"13,045 dollars"
126,Clark Atlanta University,"3,911",55%,940-1080,17-20,3.05,"27,931 dollars"
127,Chapman University,"9,608",56%,1190-1380,25-31,3.68,"43,767 dollars"
128,College of Charleston,"10,783",78%,1080-1260,22-28,3.84,"19,764 dollars"
129,Dartmouth College,"6,572",8%,1440-1560,32-35,3.9*,"23,869 dollars"
130,University of Minnesota Twin Cities,"50,734",57%,1260-1480,26-31,3.75*,"17,279 dollars"
131,Quinnipiac University,"10,207",70%,-,-,3.4,"41,636 dollars"
132,Morgan State University,"7,712",68%,570-840,16-20,2.65,"15,998 dollars"
133,University of Utah,"33,023",62%,1143-1380,22-29,3.55,"13,739 dollars"
134,Loyola University Chicago,"17,007",67%,1130-1320,25-30,3.65,"36,388 dollars"
135,Georgia Southern University,"26,408",54%,1050-1200,20-25,3.24,"15,374 dollars"
136,Florida International University,"57,942",58%,1110-1280,23-28,3.84,"9,888 dollars"
137,University at Buffalo,"31,503",61%,1160-1340,24-29,3.2,"17,264 dollars"
138,Bucknell University,"3,668",34%,1255-1430,28-32,3.54,"39,493 dollars"
139,University of Memphis,"21,458",85%,1010-1230,19-26,3.33,"13,481 dollars"
140,Texas Christian University,"10,918",47%,1150-1350,25-31,3.68*,"37,509 dollars"
141,Alabama State University,"4,413",97%,880-1020,15-19,2.89,"13,476 dollars"
142,University of Cincinnati Main Campus,"37,886",77%,1120-1350,23-29,3.46,"19,219 dollars"
143,DePaul University,"22,437",68%,-,-,3.65,"32,022 dollars"
144,Southern Methodist University,"11,649",47%,1300-1480,29-33,3.7,"40,404 dollars"
145,CUNY Hunter College,"23,202",35%,1170-1350,-,3.1,"3,957 dollars"
146,Tulane University,"12,646",13%,1360-1520,31-33,3.5,"40,783 dollars"
147,The University of Texas at Arlington,"47,899",83%,1040-1250,20-27,3.43*,"14,445 dollars"
148,Western Carolina University,"11,639",69%,1020-1200,20-25,3.67,"12,965 dollars"
149,Mercer University,"8,740",74%,1170-1340,25-30,3.71,"21,696 dollars"
150,West Chester University of Pennsylvania,"17,527",75%,1030-1210,20-26,3.52,"19,348 dollars"
151,North Carolina A & T State University,"12,142",58%,970-1150,17-22,2.68,"9,097 dollars"
152,Tufts University,"11,586",15%,1390-1540,32-34,3.91*,"26,280 dollars"
153,Sam Houston State University,"21,213",83%,990-1140,19-23,3.25*,"13,055 dollars"
154,University of Rhode Island,"17,777",75%,1050-1240,23-28,3.3,"19,652 dollars"
155,The University of Texas at San Antonio,"32,264",77%,1030-1220,19-25,3.36*,"13,168 dollars"
156,Nova Southeastern University,"20,435",80%,1070-1280,20-28,3.79,"24,776 dollars"
157,Morehouse College,"2,206",100%,1020-1143,18-22,3.24,"28,307 dollars"
158,Illinois State University,"20,635",82%,1020-1220,20-26,3.36,"20,093 dollars"
159,University of Connecticut,"27,412",49%,1200-1410,26-32,3.74*,"20,042 dollars"
160,University of Oklahoma Norman Campus,"28,564",80%,1110-1310,23-29,3.59,"21,804 dollars"
161,Virginia Commonwealth University,"30,697",87%,1070-1260,21-28,3.58,"20,968 dollars"
162,University of North Florida,"16,776",72%,1090-1260,20-25,3.73,"9,857 dollars"
163,Wayne State University,"27,025",73%,1010-1230,21-27,3.22,"15,012 dollars"
164,California Institute of Technology,"2,233",6%,1530-1560,35-36,3.97*,"27,438 dollars"
165,Belmont University,"8,260",84%,1130-1320,24-29,3.6,"36,976 dollars"
166,University of Denver,"11,952",59%,1170-1350,26-31,3.67,"37,263 dollars"
167,Colgate University,"2,969",23%,1330-1500,31-34,3.64,"23,503 dollars"
168,Lehigh University,"6,849",32%,1280-1450,29-33,3.81*,"26,631 dollars"
169,Pomona College,"1,573",7%,1390-1540,32-35,3.89*,"18,500 dollars"
170,Mississippi State University,"21,974",54%,1070-1280,22-30,3.32,"16,471 dollars"
171,University of Rochester,"11,817",30%,1310-1500,30-34,3.8,"32,939 dollars"
172,Northern Arizona University,"31,066",85%,-,-,3.4,"14,236 dollars"
173,Washington University in St Louis,"15,852",14%,1480-1560,33-35,3.92*,"27,108 dollars"
174,Houston Community College,"57,200",100%,-,-,NA,"4,686 dollars"
175,Barnard College,"2,562",12%,1340-1520,31-34,3.84,"26,649 dollars"
176,Texas Southern University,"9,732",91%,840-1000,15-18,2.96,"14,540 dollars"
177,American University,"14,311",36%,1210-1390,27-31,3.7*,"40,469 dollars"
178,Vassar College,"2,456",24%,1370-1520,31-34,3.8,"24,811 dollars"
179,California State University East Bay,"15,628",76%,-,-,3.1,"10,902 dollars"
180,Wake Forest University,"8,401",30%,-,-,NA,"24,800 dollars"
181,University of Nevada Las Vegas,"30,457",81%,1030-1250,19-25,3.25,"12,403 dollars"
182,Montana State University,"16,814",82%,1090-1310,21-27,3.3,"16,746 dollars"
183,California State University Chico,"17,578",72%,990-1190,18-24,3.21,"14,843 dollars"
184,St Johns University New York,"21,635",72%,1090-1300,23-29,3.4,"26,993 dollars"
185,Central Michigan University,"21,622",70%,990-1200,20-26,3.32,"15,266 dollars"
186,Amherst College,"1,855",11%,1310-1520,30-34,3.91*,"16,339 dollars"
187,University of West Georgia,"13,733",59%,920-1080,18-22,3.11,"15,235 dollars"
188,University of Mississippi,"22,456",88%,1020-1250,21-29,3.5,"14,672 dollars"
189,Kean University,"14,056",69%,920-1100,17-23,3.0,"17,490 dollars"
190,Virginia State University,"4,385",95%,830-1010,15-20,2.8,"18,034 dollars"
191,Liberty University,"79,152",51%,1040-1260,21-28,3.37,"28,181 dollars"
192,Utah State University,"27,932",91%,1050-1310,21-28,3.46,"13,452 dollars"
193,Lafayette College,"2,642",31%,1250-1440,28-33,3.46,"26,810 dollars"
194,Portland State University,"25,711",96%,1000-1220,18-24,3.38,"12,710 dollars"
195,Indiana State University,"13,044",90%,-,-,3.06,"12,996 dollars"
196,Hampton University,"4,321",36%,-,-,3.3,"27,441 dollars"
197,University of California Santa Cruz,"19,700",51%,1200-1380,26-32,3.73*,"17,889 dollars"
198,California State University Fresno,"25,137",58%,940-1130,16-22,3.33,"6,002 dollars"
199,University of Dayton,"11,241",72%,1120-1320,23-29,3.64,"33,372 dollars"
200,Azusa Pacific University,"10,095",67%,1030-1260,20-26,3.64,"27,707 dollars"
201,Savannah State University,"4,077",33%,900-1030,16-19,2.74,"9,557 dollars"
202,University of North Carolina at Wilmington,"16,747",65%,1170-1320,22-27,4.06,"17,981 dollars"
203,University of Minnesota Duluth,"11,024",75%,1110-1360,21-26,3.43,"16,828 dollars"
204,University of Michigan Dearborn,"9,460",62%,1070-1300,22-29,3.54,"10,634 dollars"
205,The University of West Florida,"12,847",31%,1080-1260,22-28,3.43,"7,515 dollars"
206,Bentley University,"5,460",47%,1230-1410,27-31,3.75*,"41,582 dollars"
207,Montclair State University,"21,115",76%,990-1180,-,3.2,"15,890 dollars"
208,Radford University,"9,335",75%,-,-,3.15,"14,981 dollars"
209,Wingate University,"3,689",89%,930-1130,18-23,3.34,"19,155 dollars"
210,University of Richmond,"4,002",28%,1290-1460,30-33,3.81*,"25,282 dollars"
211,Christopher Newport University,"4,957",72%,1110-1280,22-27,3.7,"25,443 dollars"
212,Sonoma State University,"9,459",91%,970-1170,17-23,3.2,"17,086 dollars"
213,Xavier University,"7,127",76%,1070-1280,22-28,3.62,"32,429 dollars"
214,Swarthmore College,"1,559",9%,1380-1540,31-35,3.9*,"19,759 dollars"
215,Rensselaer Polytechnic Institute,"7,895",47%,1290-1490,28-34,3.81,"41,006 dollars"
216,University of Arkansas,"27,778",77%,1120-1300,23-30,3.62,"16,263 dollars"
217,Louisiana State University,"30,983",75%,1080-1310,23-29,3.45,"18,143 dollars"
218,Oakland University,"19,309",83%,1020-1230,20-27,3.37,"12,843 dollars"
219,Western Michigan University,"22,562",80%,1000-1210,19-26,3.28,"17,028 dollars"
220,Albany State University,"6,371",66%,740-890,14-18,2.94,"12,500 dollars"
221,Stephen F Austin State University,"13,144",68%,990-1180,19-24,3.26*,"12,866 dollars"
222,Butler University,"5,495",73%,1150-1330,24-30,3.77,"39,923 dollars"
223,Utah Valley University,"39,931",100%,-,-,3.39,"8,267 dollars"
224,Barry University,"7,186",51%,930-1080,17-21,2.92,"18,721 dollars"
225,Northern Illinois University,"17,169",48%,940-1170,19-25,3.15,"18,346 dollars"
226,Western Washington University,"16,121",90%,1060-1280,22-28,3.42,"17,728 dollars"
227,Marquette University,"11,605",83%,1120-1320,24-29,3.63*,"34,120 dollars"
228,Jacksonville University,"4,213",92%,910-1160,18-25,3.39,"24,020 dollars"
229,University of Colorado Colorado Springs,"13,123",87%,1020-1230,21-26,3.31,"16,221 dollars"
230,Pace University New York,"13,326",79%,1050-1230,21-27,3.3,"32,492 dollars"
231,Valdosta State University,"11,211",57%,990-1140,19-23,3.15,"13,502 dollars"
232,Berry College,"2,014",71%,1090-1320,24-30,3.73,"25,192 dollars"
233,California State University Northridge,"40,212",59%,910-1130,16-22,3.18,"8,694 dollars"
234,Wheaton College,"2,944",85%,1220-1440,26-32,3.71,"28,795 dollars"
235,Brandeis University,"5,800",30%,1350-1520,30-33,3.87,"37,264 dollars"
236,Hofstra University,"10,871",68%,1160-1340,25-30,3.51,"32,975 dollars"
237,United States Naval Academy,"4,512",8%,1240-1460,26-32,3.8*,- dollars
238,Tarleton State University,"13,109",56%,950-1140,18-23,3.21*,"14,631 dollars"
239,Florida Institute of Technology,"6,271",66%,1150-1360,24-30,3.58,"32,776 dollars"
240,University of the Pacific,"6,493",66%,1120-1360,23-31,3.47,"33,178 dollars"
241,Seton Hall University,"10,162",74%,1150-1330,24-29,3.6*,"30,909 dollars"
242,Abilene Christian University,"5,204",61%,1015-1230,21-28,3.58,"27,883 dollars"
243,Ohio University Main Campus,"28,480",82%,1050-1260,21-26,3.42,"22,521 dollars"
244,University of Phoenix Online Campus,"252,238",100%,-,-,NA,"14,252 dollars"
245,Bridgewater State University,"10,990",88%,970-1150,20-25,3.2,"17,323 dollars"
246,Prairie View A & M University,"9,516",80%,870-1040,16-20,3.02,"13,460 dollars"
247,Santa Monica College,"28,800",100%,-,-,NA,"6,006 dollars"
248,University of Vermont,"13,395",67%,1180-1360,26-31,3.69*,"19,185 dollars"
249,Blinn College,"21,623",100%,-,-,NA,"13,400 dollars"

uestion 1 (8 points): Describe an interesting research question (or practical question) you have in mind, what kind of data should be collected to answer the question(s)? How many data needed for the analysis? The detail steps for collecting and save the data.

Start your college search with CollegeSimply college matching. Find the college or university that is right for you with our college search engine. Search, filter, sort and map over 3,500 U.S college profiles by GPA, SAT, ACT, major, location and admission chances to locate schools that match your profile.

https://www.collegesimply.com/colleges/search?sort=&place=&fr=&fm=&gpa=&sat=&act=&admit=comp&field=computer-and-information-sciences-and-support-services&major=&radius=300&zip=&state=&size=&tuition-fees=&net-price=&start=0